# Generated by Django 2.1.7 on 2019-04-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='link',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
